innolitics/n2y

README.md
n2y/main.py

@xaker00 it didn't seem like we need to use the name column argument when we generate YAML. What do you think?

Don't use the name column argument when generating YAML

---

n2y/main.py
n2y/notion.py
n2y/utils.py
tests/test_end_to_end.py

Closes https://github.com/innolitics/n2y/issues/36

Add support for "sorts" and "filters" on databases

---

README.md
n2y/blocks.py
n2y/mentions.py
n2y/notion.py
n2y/notion_mocks.py
n2y/rich_text.py
tests/test_blocks.py

This should be self explanatory; I needed this for a plugin I am writing

Add block references

---

README.md
n2y/notion_mocks.py
n2y/plugins/linkedheaders.py
n2y/plugins/mermaid.py
tests/notion_mocks.py
tests/test_blocks.py
tests/test_linkedheaders.py

Closes https://github.com/innolitics/n2y/issues/50

Add linked block headers plugin

---

README.md
n2y/audit.py
n2y/page.py
n2y/utils.py
setup.py
tests/test_audit_end_to_end.py
tests/test_end_to_end.py
tests/test_utils.py
tests/utils.py

Write an audit tool

---

README.md
n2y/blocks.py
tests/test_blocks.py
tests/test_end_to_end.py

Closes https://github.com/innolitics/n2y/issues/61

Add support for ColumnBlock and ColumnListBlock

---

n2y/rich_text.py
tests/test_plain_text_to_pandoc.py

I added these tests while trying to debug an issue.

Add more tests for plain_text_to_pandoc

---

n2y/plugins/mermaid.py

I need to be able to set some puppeteer flags for heroku.

Add --puppeteerConfigFile to mermaid plugin

---

README.md
n2y/notion.py
setup.py

…hen copying database children
N/A
N/A
N/A
N/A
N/A

Fix bug by conditionally deleting the id property of property types when copying database children 

---

n2y/blocks.py

stop throwing errors for empty child lists

---

README.md
n2y/plugins/hiddenjinjatoggles.py
tests/test_blocks.py
tests/test_hiddenjinjatoggles.py
tests/utils.py

Pull Out Content of Blue Toggleblocks

---

n2y/database.py
n2y/notion.py
tests/test_append_children.py
tests/test_end_to_end.py

managed cached pages

---

n2y/plugins/render.py

load default datapoints

---

n2y/notion.py

pinpoint page class check

---

n2y/notion.py
n2y/plugins/expandbluetoggles.py
n2y/plugins/hiddenjinjatoggles.py
n2y/plugins/jinjarenderpage.py
tests/test_end_to_end.py
tests/test_expandbluetoggles.py
tests/test_first_pass_output.py
tests/test_jinjarenderpage.py
tests/test_utils.py
tests/utils.py

Debug jinja render, hiddenjinjatoggle, and retry functionality

---

README.md
n2y/plugins/jinjarenderpage.py
n2y/utils.py
tests/test_jinjarenderpage.py
tests/test_utils.py

Add error handling and syntax error test to jinjarenderpage plugin

---

n2y/blocks.py
n2y/mentions.py
n2y/notion_mocks.py
n2y/rich_text.py
tests/test_expandbluetoggles.py
tests/test_rich_text.py

Debug Rich Text Array Prepend Method

---

n2y/database.py
n2y/main.py

save newly instantiated db children in list

---

n2y/notion.py

edit error retry error response

---

n2y/errors.py
n2y/main.py
n2y/notion.py
n2y/utils.py
tests/test_utils.py

Fix retries

---

.github/workflows/release.yml
.github/workflows/tests.yml
.gitignore
README.md
n2y/config.py
n2y/export.py
n2y/main.py
n2y/notion.py
n2y/notion_mocks.py
n2y/page.py
n2y/plugins/jinjarenderpage.py
n2y/property_values.py
n2y/rich_text.py
n2y/utils.py
setup.py
tests/test_append_end_to_end.py
tests/test_blocks.py
tests/test_end_to_end.py
tests/test_jinjarenderpage.py
tests/test_property_values.py
tests/test_rich_text.py
tests/test_utils.py
tests/utils.py

@samanhg47 please read through these commits carefully and study the comment messages. Try to ask yourself why I made the changes I did and the ask me about them next time we talk. Note I may merge this before you finish your review if its blocking me.
N/A as there were none.
Makes some big improvements to the architecture.

Davids big refactor

---

n2y/config.py
n2y/utils.py
tests/test_blocks.py

specify columns pandoc option

---

README.md

- Add new "Developer Tools" section after "Contributing" section.
- Add "Pandoc" subsection to "Developer Tools" describing how to use the `pandoc` CLI to emit AST output from markdown input.

Add `pandoc` CLI usage for developers content.

---

README.md

- add link to pandoc's 2.9.12 github release page
- add link to mermaid's main github page
- add hint to install mermaid at a specific version
- update mermaid to v9.4.0 following .github/workflows/tests.yml

Add dependency CLIs install details to README.md

---

n2y/errors.py
n2y/export.py
n2y/file.py
n2y/plugins/dbfootnotes.py
n2y/plugins/jinjarenderpage.py
tests/test_end_to_end.py

Misc changes

---

n2y/utils.py

select file extention from base_type variable

---

n2y/main.py
n2y/plugins/jinjarenderpage.py

refactor and debug fuzzy_find_in and dynamically create yaml file parent folder if necessary

---

n2y/utils.py
tests/test_utils.py

`header_id_from_text()` has been adjusted to meet the spec designated by https://pandoc.org/MANUAL.html#extension-auto_identifiers. `test_header_id_from_text()` and `test_header_id_from_text_existing_ids()` have also been opened up (no longer xfail) and now pass. A few additions were made to each test for more complete testing.
- [N/A] **SOUP/OTS Software:** Any new dependencies have appropriate licenses and are documented or pinned in requirements files.
- [N/A] **End-to-End Tests:** End-to-end tests have been extended or updated, if appropriate.
- [N/A] **High-Level Documentation:** The README is updated, as appropriate.
- [?] …

Adjust to meet spec

---

n2y/plugins/jinjarenderpage.py

adjust list_matches function to handle possible plurals

---

.gitignore
n2y/blocks.py
n2y/main.py
n2y/utils.py

Render empty pages

---

n2y/blocks.py
n2y/plugins/jinjarenderpage.py
tests/test_jinjarenderpage.py

Simple updates

---

n2y/blocks.py
tests/test_blocks.py

add figure flag to images with captions

---

.github/pull_request_template.md

Add description and test plan sections

---

n2y/user.py
tests/test_end_to_end.py

Add email to user if it exists
I ran the comments worker, which was throwing an error, and made sure the error was no longer thrown

nail down user email assignment conditional statement

---

n2y/blocks.py
n2y/page.py
n2y/plugins/jinjarenderpage.py
tests/test_blocks.py
tests/test_end_to_end.py

I built and implemented a table of contents block and a table of contents item block.
I built a config file (see Figure 1) for a page with a table of contents notion block, then exported it and tweaked the code in succession until it worked as expected (see Figure 2). I then wrote tests for the `TableOfContentsItemBlock` and `TableOfContentsBlock` classes [here](https://github.com/innolitics/n2y/pull/146/files#diff-c35ecd7f598a9ea24ee0b03107fa01b029252319eb42e12baf6c438bbe22dcebR685-R724) so that if they are changed, we can identify which is causing the problem more effectively.

Build and implement TableOfContentsBlock class

---

n2y/plugins/jinjarenderpage.py
tests/test_jinjarenderpage.py

Utilize changes made in [this PR](https://github.com/innolitics/n2y/pull/147) to create more precise error logs for Jinja template exceptions, specifying the messages for multiple common exceptions.
I wrote unit tests and modified existing ones to test for the specified error messages and modified the code base so that it passed said tests.

Jinja exc handle

---

n2y/notion.py

- Never return Nonetype from `Client().wrap_notion_user`
- add new `request_id` notion datapoint to bad keys
Made sure all tests were passing again, installed this branch on medtechos and tested specific-dx workspace export

fix User as property value bug

---

n2y/blocks.py
tests/test_end_to_end.py

Assign filename from text pulled from aws url
I added a check for the desired name in the end to end all blocks test and exported a page with a uploaded file (screenshot below).

pull filename from aws url

---

n2y/notion_mocks.py
n2y/user.py

add mock function for notion comment data
N/A

add mock function for notion comment data

---

n2y/notion.py
n2y/page.py
n2y/properties.py
n2y/property_values.py
tests/test_property_values.py

I added the necessary blocks to handle `status` properties and property values.
I added a test for the new property value

add blocks and tests for the status property

---

README.md
setup.py

Update to v0.8.2 and update readme
N/A

update to v0.8.2

---

n2y/logger.py

Add info to logs for debugging ease
I just simply ran medtech os with the new program

add info to log

---

tests/test_plugin_downloadfileproperty.py

Write tests to confirm the functionality of the `n2y.plugins.downloadfileproperty` module.
Ensure that the tests test for expected functionality and ultimately pass.

Add tests for the `DownloadFileProperty` plugin

---

n2y/blocks.py

Comment out unshared synced block warning
N/A

Comment out unshared synced block warning

---

README.md
n2y/properties.py
n2y/property_values.py
tests/test_property_values.py

- Create `Property` and `PropertyValue` classes for "unique_id" types
- Create tests for the `UniqueIdPropertyValue` class

Create `Property` and `PropertyValue` classes for "unique_id" types

---

n2y/notion.py

Reinstate downloaded file content hashing
N/A

Hash saved files if no block id is provided

---

n2y/plugins/jinjarenderpage.py

I created a custom Jinja test called "search" which uses the `regex_search` function to test a given value with a given pattern via `re.search`.
Ensure that all tests are still passing.

Replace removed Jinja2 test "search" with a custom one.
